#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1
PROG=/usr/sbin/smcrouted

start_service() {
	sleep 4
	ifconfig eth0 promisc
	ifconfig wpan0 promisc
	/lib/br-config.sh
	/lib/br-omr-enable.sh
	/lib/br-smcroute-prefix.sh
	/lib/install-multicast-commands.sh
	procd_open_instance
	procd_set_param command $PROG -n
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_close_instance
}
