#!/bin/bash
#
#  Copyright (c) 2018, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
# Test generating steering data.
#
set -e
set -x

readonly COMPUTER="${top_builddir}/tools/steering-data"

die()
{
  exit_message="$@"
  echo " *** ERROR: " "$@"
  exit 1
}

main()
{
    "${COMPUTER}" | grep -q 'SYNTAX' || die "No help information found!"
    ! "${COMPUTER}" 32 18b4300000000002 || die "Validation error expected!"
    ! "${COMPUTER}" 0 18b4300000000002 || die "Validation error expected!"
    ! "${COMPUTER}" -1 18b4300000000002 || die "Validation error expected!"
    [[ "$("${COMPUTER}" 1)" = 00 ]] || die "Wrong steering data!"
    [[ "$("${COMPUTER}" 18b4300000000002)" = 00000000000000000000000000000012 ]] || die "Wrong steering data!"
    [[ "$("${COMPUTER}" 16 18b4300000000002)" = 00000000000000000000000000000012 ]] || die "Wrong steering data!"
    [[ "$("${COMPUTER}" 18b4300000000002 18b4300000000003)" = 00000000000008002000000000000012 ]] || die "Wrong steering data!"
    [[ "$("${COMPUTER}" 16 18b4300000000002 18b4300000000003)" = 00000000000008002000000000000012 ]] || die "Wrong steering data!"
}

main "$@"
