#!/bin/bash
#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
# Test otbr rest server
#

set -euxo pipefail

on_exit()
{
    local status=$?

    sudo killall otbr-agent || true
    sudo killall expect || true
    sudo killall ot-cli-ftd || true
    sudo killall ot-cli-mtd || true

    return "${status}"
}

main()
{
    sudo "${CMAKE_BINARY_DIR}"/src/agent/otbr-agent -d 7 -v -I wpan0 "spinel+hdlc+forkpty://$(command -v ot-rcp)?forkpty-arg=1" &
    trap on_exit EXIT
    sleep 5
    expect <<EOF &
spawn ot-cli-ftd 2
send "masterkey 10112233445566778899aabbccddeefe\r\n"
expect "Done"
send "networkname hello\r\n"
expect "Done"
send "channel 20\r\n"
expect "Done"
send "panid 0xface\r\n"
expect "Done"
send "extpanid dead00beef00cafe\r\n"
expect "Done"
send "ifconfig up\r\n"
expect "Done"
send "thread start\r\n"
expect "Done"
wait
EOF
    expect <<EOF &
spawn ot-cli-ftd 3
send "masterkey 10112233445566778899aabbccddeefe\r\n"
expect "Done"
send "networkname hello\r\n"
expect "Done"
send "channel 20\r\n"
expect "Done"
send "panid 0xface\r\n"
expect "Done"
send "extpanid dead00beef00cafe\r\n"
expect "Done"
send "ifconfig up\r\n"
expect "Done"
send "thread start\r\n"
expect "Done"
wait
EOF
    sleep 10
    sudo python3 "${CMAKE_CURRENT_SOURCE_DIR}"/test_rest.py
}

main "$@"
