#!/bin/sh
#
#  Copyright (c) 2018, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

set -e
set -x

check_otbr_agent() {
    sudo dbus-send --system             \
        --dest=org.freedesktop.DBus     \
        --type=method_call              \
        --print-reply                   \
        /org/freedesktop/DBus           \
        org.freedesktop.DBus.ListNames | grep -q '"otbr.agent'
}

main() {
    RELEASE=1 ./script/bootstrap
    ./script/bootstrap
    NAT64=1 ./script/setup
    SOCAT_OUTPUT=/tmp/ot-socat

    socat -d -d pty,raw,echo=0 pty,raw,echo=0 > /dev/null 2> $SOCAT_OUTPUT &
    while true; do
        if test $(head -n2 $SOCAT_OUTPUT | wc -l) = 2; then
            DEVICE_PTY=$(head -n1 $SOCAT_OUTPUT | grep -o '/dev/.\+')
            WPANTUND_PTY=$(head -n2 $SOCAT_OUTPUT | tail -n1 | grep -o '/dev/.\+')
            break
        fi
        echo 'Waiting for socat ready...'
        sleep 1
    done
    echo 'DEVICE_PTY' $DEVICE_PTY
    echo 'WPANTUND_PTY' $WPANTUND_PTY
    # default configuration for Thread device is /dev/ttyUSB0
    sudo ln -s $WPANTUND_PTY /dev/ttyUSB0 || die 'Failed to create ttyUSB0!'

    ot-ncp-ftd 1 > $DEVICE_PTY < $DEVICE_PTY &
    ./script/console & SERVICES_PID=$!
    sudo service tayga start
    echo 'Waiting for services to be ready...'
    sleep 10
    check_otbr_agent || die 'Service otbr-agent not ready!'
    netstat -an | grep 80 || die 'Service otbr-web not ready!'
    pidof tayga || die 'tayga not running'
    kill $SERVICES_PID || die 'Failed to stop services!'
    sudo killall otbr-web || true
    sudo killall otbr-agent || true
    sudo killall wpantund || true
    sudo service tayga stop || true
    killall ot-ncp-ftd || die 'Failed to end OpenThread!'
    killall socat || die 'Failed to end socat!'
    jobs
    echo 'Waiting for services to end...'
    wait
}

main "$@"
