#!/bin/bash
#
#  Copyright (c) 2019, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
# Test build and run mdns using mojo
#

set -x
set -e


main() 
{
    OTBR_DIR=${OTBR_DIR:-$(pwd)}
    BUILD_DIR=${OTBR_DIR}/build/chromium
    CHROMIUM_DIR=${BUILD_DIR}/chromium

    if [ -f "${BUILD_DIR}" ] || [ -d "${BUILD_DIR}" ]; then
        rm -rf "${BUILD_DIR}"
    fi
    mkdir -p "${BUILD_DIR}" && cd "${BUILD_DIR}"

    git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git --depth=1

    export PATH="${BUILD_DIR}/depot_tools:${PATH}"

    mkdir -p "${CHROMIUM_DIR}" && cd "${CHROMIUM_DIR}"
    fetch --nohooks --no-history chromium

    # sync test code
    MOJO_TEST_SRC_DIR=${CHROMIUM_DIR}/src/mdns_mojo_test
    cp -r "${OTBR_DIR}/tests/mdns/mdns_mojo_test" "${CHROMIUM_DIR}/src/"
    ln -s "${OTBR_DIR}/third_party/chromecast/mojom/mdns.mojom" "${MOJO_TEST_SRC_DIR}/public/mojom/mdns.mojom"
    ln -s "${OTBR_DIR}/src/agent/mdns.hpp" "${MOJO_TEST_SRC_DIR}/mdns.hpp"
    ln -s "${OTBR_DIR}/src/agent/mdns_mojo.hpp" "${MOJO_TEST_SRC_DIR}/mdns_mojo.hpp"
    ln -s "${OTBR_DIR}/src/agent/mdns_mojo.cpp" "${MOJO_TEST_SRC_DIR}/mdns_mojo.cpp"
    ln -s "${OTBR_DIR}/src/common" "${MOJO_TEST_SRC_DIR}/common"

    cd /etc/apt/sources.list.d && sudo rm -rf cassandra.list* couchdb.list* mongodb-3.4.list* rabbitmq_rabbitmq-server.list* chris-lea-redis-server.list* github_git-lfs.list*
    cd "${CHROMIUM_DIR}/src"
    # Required to install seperately on travis
    sudo apt-get -y install gcc-multilib g++-multilib
    sudo ./build/install-build-deps.sh
    gclient runhooks

    sed -i -e '/"\/\/url:url_unittests",/a \    "\/\/mdns_mojo_test:mdns_mojo_client",\n    "\/\/mdns_mojo_test:mdns_mojo_stub_service",\n    "\/\/mdns_mojo_test:standalone_mojo_broker_lite",' "${CHROMIUM_DIR}/src/BUILD.gn"

    gn gen out/Default --args="use_ozone=true"
    autoninja -C out/Default mdns_mojo_test:mdns_mojo_client mdns_mojo_test:mdns_mojo_stub_service mdns_mojo_test:standalone_mojo_broker_lite

    ./out/Default/standalone_mojo_broker_lite &
    BROKER_PID=$!
    ./out/Default/mdns_mojo_stub_service &
    SERVICE_PID=$!
    ./out/Default/mdns_mojo_client
    kill -INT "${BROKER_PID}"
    kill -INT "${SERVICE_PID}"
}

main "$@"
