#!/bin/sh
#
#  Copyright (c) 2018, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

#
# This script includes common utils for testing mdns
#

readonly DNS_SD_RESULT=result

on_exit()
{
    readonly EXIT_CODE=$?

    kill "$PID"
    [[ ! -e "${DNS_SD_RESULT}" ]] || rm "${DNS_SD_RESULT}" || true

    exit $EXIT_CODE
}

#######################################
# Check if a service is regisered
#
# Arguments:
#   $1  Name
#   $2  Type
#   $3  Text record
#
# Returns:
#   0           Registered
#   otherwise   Not registered
#######################################
dns_sd_check()
{
    local ret

    ret=0

    # dns-sd will not exit
    dns-sd -L "$1" "$2" local 2>&1 > "${DNS_SD_RESULT}" & DNS_SD_PID=$!
    sleep 1
    kill "${DNS_SD_PID}"

    cat "${DNS_SD_RESULT}"
    grep -q "$3" "${DNS_SD_RESULT}" || ret=1

    return ${ret}
}

#######################################
# Check if a service is regisered
#
# Arguments:
#   $1  Expected avahi query result string
#
# Returns:
#   0           Registered
#   otherwise   Not registered
#######################################
avahi_check()
{
    local ret

    ret=0

    avahi-browse -aprt
    avahi-browse -aprt | grep -q "$1" || ret=1

    return ${ret}
}
