#!/bin/bash

customise_dhcpcd_conf()
{
    # This has to be run after script/_border_routing, and this will
    # invalidate all changes to dhcpcd.conf made by script/_border_routing.
    sudo tee /etc/dhcpcd.conf >/dev/null <<EOF
noipv6rs 
# disable router solicitation
interface eth0
  iaid 1
  ia_pd 2/::/64 -
EOF
}

dhcpv6_pd_ref_uninstall()
{
    with DHCPV6_PD_REF || return 0

    if [[ -f "/etc/dhcpcd.conf.orig" ]]; then
        sudo mv /etc/dhcpcd.conf.orig /etc/dhcpcd.conf
    fi
    sudo systemctl restart dhcpcd
    sudo rm -f /etc/dhcpcd.enter-hook /etc/dhcpcd.exit-hook

}

dhcpv6_pd_ref_install()
{
    with DHCPV6_PD_REF || return 0

    if [[ -f "/etc/dhcpcd.conf" ]]; then
        sudo mv /etc/dhcpcd.conf /etc/dhcpcd.conf.orig
    fi
    customise_dhcpcd_conf
    # Add dhcpcd.hooks
    sudo install -m 755 "$(dirname "$0")"/reference-device/dhcpcd.enter-hook /etc/dhcpcd.enter-hook
    sudo install -m 755 "$(dirname "$0")"/reference-device/dhcpcd.exit-hook /etc/dhcpcd.exit-hook
}
