#! /bin/bash

ETC_SUDOERS=/etc/sudoers

# Assume we are not to extend the time
SUDO_EXTEND_TIME=${SUDO_EXTEND_TIME:-false}

# measurement is minutes, 120 = 2 hours
SUDO_EXTEND_TIME_AMOUNT=120

extend_sudo_timeout()
{
    local _why
    _why="Disabled"

    if ${SUDO_EXTEND_TIME}
    then
	# do not repeat!
	sudo grep -s '^Defaults\s\s*timestamp_timeout' ${ETC_SUDOERS} > /dev/null
	if [ $? == 0 ]
        then
            SUDO_EXTEND_TIME=false
	    _why="Already present"
	fi
    fi

    if ${SUDO_EXTEND_TIME}
    then
	echo "Extending sudo timeout..."
        sudo /bin/sh -c "echo \"Defaults timestamp_timeout=${SUDO_EXTEND_TIME_AMOUNT}\" >> ${ETC_SUDOERS}"
    else
	echo "sudo-timeout: Not extending, ${_why}"
    fi
}

