#!/bin/sh
#
#  Copyright (c) 2017, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

wpantund_uninstall()
{
    sudo killall wpantund || true

    test -d $BUILD_DIR/wpantund || return 0

    (cd $BUILD_DIR/wpantund &&
        (test ! -f config.status || sudo make uninstall))
}

wpantund_install()
{
    CLONE_ARGS=""

    if [ -z "$WPANTUND_COMMIT" ]; then
        CLONE_ARGS="--depth 1"
    fi

    test -d $BUILD_DIR/wpantund || (cd $BUILD_DIR &&
        git clone $CLONE_ARGS https://github.com/openthread/wpantund.git) || die 'Failed to download source code of wpantund!'

    (cd $BUILD_DIR/wpantund &&
	((test -n "$WPANTUND_COMMIT" && git reset $WPANTUND_COMMIT --hard) || echo "WPANTUND_COMMIT value has not been set or something went wrong during switching to the set commit.") &&
        (test -f configure || ./bootstrap.sh) &&
        (test -f config.status || ./configure --prefix=/usr --sysconfdir=/etc \
        --disable-ncp-dummy --enable-static-link-ncp-plugin=spinel) &&
        make && sudo make install &&
        sudo sed -i '/Config:NCP:SocketPath "\/dev/i Config:NCP:SocketPath "/dev/ttyUSB0"' /etc/wpantund.conf) || die 'Failed to install wpantund!'
}

wpantund_update()
{
    test ! -d $BUILD_DIR/wpantund || (cd $BUILD_DIR/wpantund &&
        REMOTE_COMMIT=$(git ls-remote https://github.com/openthread/wpantund.git refs/heads/master | cut -f1) &&
        LOCAL_COMMIT=$(git rev-parse HEAD) &&
        cd .. &&
        (test "$REMOTE_COMMIT" = "$LOCAL_COMMIT" || rm -frv wpantund))

    wpantund_install
}
