#!/bin/bash
#
#  Copyright (c) 2021, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

#
#  This script calls cmake and ninja to compile otbr-agent or ot-extcap.
#
#  Compile with default build options (otbr):
#
#      script/cmake-build
#
#  Compile extcap project:
#
#      script/cmake-build extcap
#
#  Compile with specified build option enabled:
#
#      script/cmake-build -D${option}=ON
#
#  Compile with specified ninja build target:
#
#      OTBR_TARGET="${target}" script/cmake-build
#
#  Compile with specified build directory:
#
#      OTBR_BUILD_DIR="./build/temp" script/cmake-build
#
#  Examples:
#
#      script/cmake-build
#
#      script/cmake-build extcap
#
#      script/cmake-build -DOTBR_DBUS=ON
#
#      OTBR_BUILD_DIR="./build/temp" OTBR_TARGET="otbr-agent" script/cmake-build -DOTBR_DBUS=ON
#

# shellcheck source=script/_initrc
. "$(dirname "$0")"/_initrc

OTBR_TOP_SRCDIR="$PWD"
readonly OTBR_TOP_SRCDIR

OTBR_TARGET=${OTBR_TARGET-}

main()
{
    local project="otbr"

    if [[ $# -gt 0 && ($1 == "extcap" || $1 == "otbr") ]]; then
        project="$1"
        shift
    fi

    local srcdir="${OTBR_TOP_SRCDIR}"
    local default_builddir="${BUILD_DIR}/${project}"

    if [[ ${project} == "extcap" ]]; then
        srcdir="${OTBR_TOP_SRCDIR}/tools/extcap"
    fi

    local builddir="${OTBR_BUILD_DIR:-${default_builddir}}"

    mkdir -p "${builddir}"

    (
        cd "${builddir}" || die "Failed to enter ${builddir}"

        cmake -GNinja -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_EXPORT_COMPILE_COMMANDS=ON "${srcdir}" "$@"

        if [[ -n ${OTBR_TARGET[*]} ]]; then
            ninja "${OTBR_TARGET[@]}"
        else
            ninja
            if [[ ${project} == "extcap" ]]; then
                cpack -G DEB
            fi
        fi
    )
}

main "$@"
