#!/bin/bash
#
#  Copyright (c) 2017, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#   Description:
#       This script starts all border router services.
#

# shellcheck source=script/_initrc
. "$(dirname "$0")"/_initrc
. script/_nat64
. script/_dns64
. script/_firewall

OTBR_MDNS="${OTBR_MDNS:-mDNSResponder}"
OT_BACKBONE_CI="${OT_BACKBONE_CI:-0}"
REFERENCE_DEVICE="${REFERENCE_DEVICE:-0}"

startup()
{
    # shellcheck source=/dev/null
    . "$BEFORE_HOOK"
    sudo sysctl --system
    nat64_start || die 'Failed to start NAT64!'
    dns64_start || die 'Failed to start DNS64!'
    firewall_start || die 'Failed to start firewall'

    start_service rsyslog
    start_service dbus
    # Thread Certification tests require Avahi to publish records for tests. Since the
    # same image is used for all tests Avahi needs to be started here and if
    # building a reference device.
    if [[ ${OTBR_MDNS} == "avahi" || ${OT_BACKBONE_CI} == 1 || ${REFERENCE_DEVICE} == 1 ]]; then
        start_service avahi-daemon
    fi
    if have service; then
        sudo service mdns status || sudo service mdns start || echo "service mdns is not available!"
    fi
    without WEB_GUI || start_service otbr-web
    start_service otbr-agent

    # shellcheck source=/dev/null
    . "$AFTER_HOOK"
}

shutdown()
{
    nat64_stop || echo 'Failed to stop NAT64!'
    dns64_stop || echo 'Failed to stop DNS64!'
    firewall_stop || echo 'Failed to stop firewall'

    stop_service rsyslog
    stop_service dbus
    if [[ ${OTBR_MDNS} == "avahi" || ${OT_BACKBONE_CI} == 1 || ${REFERENCE_DEVICE} == 1 ]]; then
        systemctl is-active avahi-daemon && sudo systemctl stop avahi-daemon || echo 'Failed to stop avahi!'
    fi
    if have service; then
        stop_service mdns
    fi
    without WEB_GUI || stop_service otbr-web
    stop_service otbr-agent
}

main()
{
    if [[ ${1-} == "shutdown" ]]; then
        shift
        shutdown "$@"
    else
        startup "$@"
    fi
}

main "$@"
