#!/bin/bash
#
#  Copyright (c) 2025, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

set -euxo pipefail

MDNS_RESPONDER_SOURCE_NAME="mDNSResponder-1790.80.10"
MDNS_RESPONDER_URL="https://github.com/apple-oss-distributions/mDNSResponder/archive/refs/tags/${MDNS_RESPONDER_SOURCE_NAME}.tar.gz"
MDNS_RESPONDER_BUILD_DIR="/tmp/${MDNS_RESPONDER_SOURCE_NAME}"

MDNS_RESPONDER_PATCH_PATH="${1}"

mdns_responder_install()
{
    wget --no-check-certificate -O "${MDNS_RESPONDER_SOURCE_NAME}.tar.gz" "${MDNS_RESPONDER_URL}"
    mkdir -p "${MDNS_RESPONDER_BUILD_DIR}"
    tar xvf "${MDNS_RESPONDER_SOURCE_NAME}.tar.gz" -C "${MDNS_RESPONDER_BUILD_DIR}" --overwrite --strip-components=1

    cd "${MDNS_RESPONDER_BUILD_DIR}"
    for patch in "${MDNS_RESPONDER_PATCH_PATH}"/*.patch; do
        patch -p1 <"${patch}"
    done

    # Build and install
    cd mDNSPosix
    make os=linux tls=no
    sudo make install os=linux tls=no
}

mdns_responder_install
