#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

name: Build

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || (github.repository == 'openthread/ot-br-posix' && github.run_id) || github.ref }}
  cancel-in-progress: true

jobs:

  pretty:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Bootstrap
      run: BUILD_TARGET=pretty-check tests/scripts/bootstrap.sh
    - name: Check
      run: script/make-pretty check

  check:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        build_type: ["Debug", "Release"]
        mdns: ["mDNSResponder", "avahi"]
    env:
      BUILD_TARGET: check
      OTBR_BUILD_TYPE: ${{ matrix.build_type }}
      OTBR_MDNS: ${{ matrix.mdns }}
      OTBR_OPTIONS: "-DOTBR_SRP_ADVERTISING_PROXY=ON -DOTBR_BORDER_ROUTING=ON -DOTBR_NAT64=ON -DOTBR_DHCP6_PD=ON -DOTBR_SRP_SERVER_AUTO_ENABLE=OFF -DOTBR_TREL=ON"
      OTBR_COVERAGE: 1
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Bootstrap
      run: tests/scripts/bootstrap.sh
    - name: Run
      run: script/test build check
    - name: Codecov
      uses: codecov/codecov-action@v5

  rest-check:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rest: ["rest-off", ""]
    env:
      BUILD_TARGET: check
      OTBR_REST: ${{ matrix.rest }}
      OTBR_MDNS: mDNSResponder
      OTBR_OPTIONS: "-DOTBR_SRP_ADVERTISING_PROXY=ON -DOTBR_DNSSD_DISCOVERY_PROXY=ON -DOTBR_TREL=ON"
      OTBR_COVERAGE: 1
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Bootstrap
      run: tests/scripts/bootstrap.sh
    - name: Run
      run: script/test build check
    - name: Codecov
      uses: codecov/codecov-action@v5

  script-check:
    runs-on: ubuntu-20.04
    env:
      BUILD_TARGET: script-check
      OTBR_COVERAGE: 1
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Bootstrap
      run: tests/scripts/bootstrap.sh
    - name: Run
      run: tests/scripts/check-scripts
    - name: Codecov
      uses: codecov/codecov-action@v5

  scan-build:
    runs-on: ubuntu-20.04
    env:
      BUILD_TARGET: scan-build
      CC: clang
      CXX: clang++
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Bootstrap
      run: tests/scripts/bootstrap.sh
    - name: Run
      run: tests/scripts/check-scan-build

  package:
    runs-on: ubuntu-20.04
    env:
      BUILD_TARGET: package
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Bootstrap
      run: |
        tests/scripts/bootstrap.sh
        sudo pip3 install -U scikit-build
        sudo pip3 install -U cmake==3.10.3
        cmake --version | grep 3.10.3
    - name: Build
      run: script/test package

  simulation:
    runs-on: ubuntu-latest
    env:
      BUILD_TARGET: check
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Bootstrap
      run: tests/scripts/bootstrap.sh
    - name: Build
      run: |
        script/bootstrap
        script/test build
    - name: Run
      run: |
        script/test simulation
